import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { slots, indiaDate } from '../src/lib/shared.js';
let db;
const staff = '11111111-1111-4111-8111-111111111111', visitor = '22222222-2222-4222-8222-222222222222';
function day(offset=4) { const d = new Date(); d.setDate(d.getDate()+offset); while(d.getDay()===0) d.setDate(d.getDate()+1); return indiaDate(d); }
async function add(date,time=slots[0],id=crypto.randomUUID()) { return db.query(`insert into public.bookings (id,customer_name,mobile_number,whatsapp_number,email,car_manufacturer,car_model,manufacturing_year,fuel_type,booking_type,booking_date,booking_time,requirement,preferred_contact_method) values ($1,'Test Customer','9876543210','9876543210','test@example.com','Test passenger car','Test model',2020,'Petrol','Car Silencer Inspection',$2,$3,'Silencer enquiry','WhatsApp') returning *`,[id,date,time]); }
before(async () => {
  db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create schema storage; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema public, auth to anon, authenticated, service_role; grant execute on function auth.uid() to anon,authenticated,service_role; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]); create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text); alter table storage.objects enable row level security; grant usage on schema storage to authenticated, anon, service_role; grant select on storage.objects to authenticated,anon;`);
  await db.exec(await readFile(new URL('../supabase/setup.sql',import.meta.url),'utf8'));
  await db.query('insert into auth.users values ($1),($2)',[staff,visitor]);
  await db.query('insert into public.admin_users(user_id) values ($1)',[staff]);
});
after(async () => { await db?.close(); });
test('Schema has all required booking columns, private photos and RLS on every public table',async () => { const cols = await db.query("select column_name from information_schema.columns where table_schema='public' and table_name='bookings'"); for (const key of ['id','booking_reference','uploaded_image_url','status','created_at','booking_time','whatsapp_number']) assert.ok(cols.rows.some(r=>r.column_name===key)); const tables=await db.query("select relname,relrowsecurity from pg_class join pg_namespace n on n.oid=relnamespace where n.nspname='public' and relkind='r'"); assert.ok(tables.rows.every(r=>r.relrowsecurity)); const bucket=await db.query('select public from storage.buckets'); assert.equal(bucket.rows[0].public,false); });
test('Database reserves once, rejects duplicate slots, releases cancelled slots',async () => { const date=day(4); const first=(await add(date)).rows[0]; assert.match(first.booking_reference,/^RECO-[A-F0-9]{12}$/); await assert.rejects(add(date),/duplicate key/); await db.query("update public.bookings set status='Cancelled' where id=$1",[first.id]); const next=(await add(date)).rows[0]; assert.notEqual(first.booking_reference,next.booking_reference); });
test('Sunday, past dates and already elapsed slots cannot be inserted',async () => { const d=new Date(); while(d.getDay()!==0) d.setDate(d.getDate()+1); await assert.rejects(add(indiaDate(d)),/Sundays/); await assert.rejects(add('2020-01-01'),/future time/); });
test('Date and time blocks prevent reservations and cannot overwrite a booking',async () => { const date=day(10); await db.query("insert into public.booking_blocks(block_date,reason) values ($1,'Closed')",[date]); await assert.rejects(add(date),/unavailable/); const next=day(13); await db.query("insert into public.booking_blocks(block_date,booking_time,reason) values ($1,$2,'Unavailable')",[next,slots[0]]); await assert.rejects(add(next),/unavailable/); await add(next,slots[1]); await assert.rejects(db.query("insert into public.booking_blocks(block_date,reason) values ($1,'Closed')",[next]),/Reschedule or cancel/); });
test('Rescheduling rejects occupied dates and preserves the original reservation',async () => { const date=day(20); const a=(await add(date,slots[0])).rows[0]; await add(date,slots[1]); await assert.rejects(db.query('update public.bookings set booking_time=$1 where id=$2',[slots[1],a.id]),/duplicate key/); const result=await db.query('select booking_time from public.bookings where id=$1',[a.id]); assert.equal(result.rows[0].booking_time,slots[0]); });
test('Anonymous visitors cannot read, edit, delete or directly insert customer records',async () => { await db.exec('set role anon'); try { for (const sql of ['select * from public.bookings','delete from public.bookings',"update public.bookings set status='Cancelled'","insert into public.bookings default values",'select * from public.enquiries','select * from public.admin_users']) await assert.rejects(db.query(sql),/permission denied/); const photos=await db.query('select * from storage.objects'); assert.deepEqual(photos.rows,[]); } finally { await db.exec('reset role'); } });
test('Ordinary authenticated user sees no bookings and cannot self-promote',async () => { await db.query("select set_config('request.jwt.claim.sub',$1,false)",[visitor]); await db.exec('set role authenticated'); try { assert.deepEqual((await db.query('select * from public.bookings')).rows,[]); assert.deepEqual((await db.query('select * from public.admin_users')).rows,[]); await assert.rejects(db.query('insert into public.admin_users(user_id) values($1)',[visitor]),/permission denied/); const changed=await db.query("update public.bookings set status='Cancelled' returning id"); assert.equal(changed.rows.length,0); } finally { await db.exec('reset role'); } });
test('Allowlisted staff can read and update bookings through RLS',async () => { await db.query("select set_config('request.jwt.claim.sub',$1,false)",[staff]); await db.exec('set role authenticated'); try { const rows=(await db.query("select * from public.bookings where status='Pending'")).rows; assert.ok(rows.length>0); await db.query("update public.bookings set status='Confirmed' where id=$1",[rows[0].id]); } finally { await db.exec('reset role'); } });
test('Atomic abuse limiter is callable by the server role only',async () => { await db.exec('set role anon'); try { await assert.rejects(db.query('select public.reco_consume_rate_limit($1)',['a'.repeat(64)]),/permission denied/); } finally { await db.exec('reset role'); } await db.exec('set role service_role'); try { for(let i=0;i<8;i++) assert.equal((await db.query('select public.reco_consume_rate_limit($1) allowed',['a'.repeat(64)])).rows[0].allowed,true); assert.equal((await db.query('select public.reco_consume_rate_limit($1) allowed',['a'.repeat(64)])).rows[0].allowed,false); } finally { await db.exec('reset role'); } });
