import { useEffect, useMemo, useState } from 'react';
import { FiArrowRight, FiDownload, FiRefreshCw, FiSearch, FiX, FiImage, FiLock, FiLogOut } from 'react-icons/fi';
import { Button, Field, SelectField, ErrorNotice, WhatsApp } from '../components/UI';
import { api, supabase, download } from '../lib/api';
import { slots, statuses, indiaDate, csvContent, prettyDate, whatsappUrl } from '../lib/shared';
export default function Admin() {
  const [session, setSession] = useState(null), [authLoading, setAuthLoading] = useState(true), [verified, setVerified] = useState(false), [login, setLogin] = useState({ email: '', password: '' }), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [rows, setRows] = useState([]), [blocks, setBlocks] = useState([]), [enquiries, setEnquiries] = useState([]), [loading, setLoading] = useState(false), [tab, setTab] = useState('bookings'), [query, setQuery] = useState(''), [date, setDate] = useState(''), [status, setStatus] = useState(''), [selectedId, setSelectedId] = useState(null), [reschedule, setReschedule] = useState({ booking_date: '', booking_time: '' }), [block, setBlock] = useState({ block_date: '', booking_time: '', reason: '' }), [image, setImage] = useState(null);
  const token = session?.access_token;
  useEffect(() => { if (!supabase) { setAuthLoading(false); return; } let current = true; supabase.auth.getSession().then(({ data, error }) => { if (current) { if (error) setError('Unable to restore your session. Please sign in again.'); setSession(data.session); setAuthLoading(false); } }); const { data } = supabase.auth.onAuthStateChange((_event, next) => { setSession(next); if (!next) { setVerified(false); setRows([]); setEnquiries([]); setBlocks([]); setImage(null); } }); return () => { current = false; data.subscription.unsubscribe(); }; }, []);
  useEffect(() => { if (!token) return; let current = true; setLoading(true); setVerified(false); setError(''); api('admin/session', { token }).then(async () => { if (!current) return; setVerified(true); const data = await Promise.all([api('admin/bookings', { token }), api('admin/blocks', { token }), api('admin/enquiries', { token })]); if (current) { setRows(data[0].bookings); setBlocks(data[1].blocks); setEnquiries(data[2].enquiries); } }).catch(e => { if (current) setError(e.message); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [token]);
  async function refresh() { setLoading(true); try { const data = await Promise.all([api('admin/bookings', { token }), api('admin/blocks', { token }), api('admin/enquiries', { token })]); setRows(data[0].bookings); setBlocks(data[1].blocks); setEnquiries(data[2].enquiries); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  async function signIn(e) { e.preventDefault(); setBusy(true); setError(''); try { const { error } = await supabase.auth.signInWithPassword(login); if (error) throw new Error('Unable to sign in. Check your email and password.'); setLogin(v => ({ ...v, password: '' })); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  async function signOut() { setError(''); const { error } = await supabase.auth.signOut(); if (error) setError('Sign-out could not be completed. Please try again.'); else { setVerified(false); setSession(null); setRows([]); setBlocks([]); setEnquiries([]); } }
  const filtered = useMemo(() => rows.filter(b => (!date || b.booking_date === date) && (!status || b.status === status) && [b.customer_name,b.mobile_number,b.car_manufacturer,b.car_model,b.booking_reference].join(' ').toLowerCase().includes(query.trim().toLowerCase())), [rows, query, date, status]);
  const selected = rows.find(r => r.id === selectedId);
  const change = setter => e => setter(v => ({ ...v, [e.target.name]: e.target.value }));
  async function mutate(path, method, body, message) { setBusy(true); setError(''); setNotice(''); try { await api(path, { method, token, body }); await refresh(); setNotice(message); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  async function openImage(id, kind) { setBusy(true); setError(''); setImage(null); try { const data = await api('admin/image', { method:'POST', token, body:{ id, kind } }); setImage({ id, url:data.url }); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  if (authLoading) return <div className="section container" role="status">Checking your session…</div>;
  if (!token || !verified) return <section className="section container"><div className="admin-login"><p className="eyebrow"><FiLock/>RECO STAFF ACCESS</p><h2>Welcome back.</h2><p>Sign in to manage booking requests and car-silencer enquiries.</p><ErrorNotice>{error}</ErrorNotice>{!supabase ? <div className="notice">Staff sign-in is not available yet. Please contact the website administrator.</div> : token ? <><p role="status">{loading ? 'Checking staff access…' : 'Access is restricted to authorized RECO staff.'}</p><Button onClick={signOut} variant="outline">Sign Out</Button></> : <form onSubmit={signIn}><Field label="Staff email" name="email" type="email" autoComplete="username" required value={login.email} onChange={change(setLogin)}/><Field label="Password" name="password" type="password" autoComplete="current-password" required value={login.password} onChange={change(setLogin)}/><Button type="submit" disabled={busy}>{busy ? 'Signing in…' : 'Sign In'}<FiArrowRight/></Button></form>}</div></section>;
  return <section className="section container"><div className="admin-header"><div><p className="eyebrow">RECO STAFF DASHBOARD</p><h1>Bookings, at a glance.</h1></div><Button variant="outline" onClick={signOut}><FiLogOut/>Sign Out</Button></div><ErrorNotice>{error}</ErrorNotice>{notice && <div className="notice notice-success" role="status">{notice}</div>}<div className="admin-stats">{statuses.map(s => <div className="stat-card" key={s}><span>{s}</span><strong>{rows.filter(r => r.status === s).length}</strong></div>)}</div><div className="admin-tabs" role="tablist" aria-label="Dashboard sections">{[['bookings','Bookings'],['availability','Availability'],['enquiries','Custom enquiries']].map(([id,label]) => <button role="tab" aria-selected={tab === id} className={tab === id ? 'active' : ''} key={id} onClick={() => { setTab(id); setImage(null); setError(''); }}>{label}</button>)}</div>
  {tab === 'bookings' && <><div className="admin-filters"><label className="searchbox"><FiSearch/><input value={query} onChange={e => setQuery(e.target.value)} aria-label="Search customers or car models" placeholder="Customer, car model or reference"/></label><Field label="Booking date" name="admin-date" type="date" value={date} onChange={e => setDate(e.target.value)}/><SelectField label="Status" name="admin-status" options={statuses} placeholder="All statuses" value={status} onChange={e => setStatus(e.target.value)}/><Button variant="outline" disabled={!filtered.length || loading} onClick={() => download(csvContent(filtered), `reco-bookings-${indiaDate()}.csv`, 'text/csv;charset=utf-8')}><FiDownload/>Export CSV</Button></div><button className="text-link" onClick={() => { setQuery(''); setDate(''); setStatus(''); }}>Clear filters</button><div className="table-wrap"><table><thead><tr><th>Reference / customer</th><th>Car</th><th>Date / time (IST)</th><th>Status</th><th>Details</th></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="table-empty">Loading bookings…</td></tr> : !filtered.length ? <tr><td colSpan={5} className="table-empty">No bookings match your filters.</td></tr> : filtered.map(b => <tr key={b.id}><td>{b.booking_reference}<small>{b.customer_name} · {b.mobile_number}</small></td><td>{b.car_manufacturer} {b.car_model}<small>{b.fuel_type} · {b.manufacturing_year}</small></td><td>{prettyDate(b.booking_date)}<small>{b.booking_time}</small></td><td><span className={`status status-${b.status.toLowerCase()}`}>{b.status}</span></td><td><Button variant="outline" onClick={() => { setSelectedId(b.id); setReschedule({ booking_date:b.booking_date, booking_time:b.booking_time }); setImage(null); }}>View</Button></td></tr>)}</tbody></table></div>
  {selected && <div className="dashboard-panel"><div className="detail-title"><h2>{selected.booking_reference}</h2><button aria-label="Close booking details" className="button button-text" onClick={() => { setSelectedId(null); setImage(null); }}><FiX/></button></div><dl className="summary-list">{[['Customer',selected.customer_name],['Mobile',selected.mobile_number],['WhatsApp',selected.whatsapp_number],['Email',selected.email],['Car',`${selected.car_manufacturer} ${selected.car_model}`],['Year & fuel',`${selected.manufacturing_year} · ${selected.fuel_type}`],['Registration',selected.registration_number || 'Not supplied'],['Booking type',selected.booking_type],['Requirement',selected.requirement],['Contact preference',selected.preferred_contact_method],['Submitted',new Date(selected.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST']].map(([k,v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="detail-actions">{['Confirmed','Completed','Cancelled'].filter(s => s !== selected.status).map(s => <Button variant="outline" disabled={busy} key={s} onClick={() => mutate(`admin/bookings/${selected.id}`,'PATCH',{status:s},`Booking marked ${s.toLowerCase()}.`)}>{s === 'Confirmed' ? 'Confirm Booking' : s === 'Completed' ? 'Mark Completed' : 'Cancel Booking'}</Button>)}<Button href={whatsappUrl(`Hello ${selected.customer_name}, this is RECO regarding your car-silencer booking ${selected.booking_reference} on ${selected.booking_date}, ${selected.booking_time} IST.`,selected.whatsapp_number || selected.mobile_number)} target="_blank" rel="noreferrer" variant="subtle">WhatsApp Customer</Button>{selected.uploaded_image_url && <Button variant="outline" disabled={busy} onClick={() => openImage(selected.id,'bookings')}><FiImage/>View Photograph</Button>}</div>{image?.id === selected.id && <img className="admin-image" src={image.url} alt="Customer’s silencer photograph" onError={() => setError('The photo link expired or could not load. Click View Photograph again.')}/>}<form className="dashboard-panel" onSubmit={e => { e.preventDefault(); mutate(`admin/bookings/${selected.id}`,'PATCH',reschedule,'Booking rescheduled. Contact the customer to share the new time.'); }}><h3>Reschedule appointment</h3><div className="form-grid"><Field label="New date" name="booking_date" type="date" min={indiaDate()} required value={reschedule.booking_date} onChange={change(setReschedule)}/><SelectField label="New time (IST)" name="booking_time" options={slots} required value={reschedule.booking_time} onChange={change(setReschedule)}/></div><p className="field-hint">The selected time is checked again when you save. Existing bookings and blocked times cannot be overwritten.</p><Button disabled={busy} type="submit">Save New Time</Button></form></div>}</>}
  {tab === 'availability' && <div className="dashboard-panel"><h2>Block an unavailable date or time</h2><p>Existing bookings must be rescheduled or cancelled before you block their time.</p><form className="admin-block-form" onSubmit={e => { e.preventDefault(); mutate('admin/blocks','POST',block,'Availability updated.'); }}><Field label="Date" name="block_date" type="date" min={indiaDate()} required value={block.block_date} onChange={change(setBlock)}/><SelectField label="Time slot" name="booking_time" placeholder="Entire day" options={slots} value={block.booking_time} onChange={change(setBlock)}/><Field label="Reason" name="reason" required maxLength={200} value={block.reason} onChange={change(setBlock)}/><Button disabled={busy} type="submit">Block Availability</Button></form><div className="admin-block-list">{loading ? <p>Loading blocks…</p> : !blocks.length ? <p>No dates or times are blocked.</p> : blocks.map(b => <div className="admin-block" key={b.id}><div><strong>{prettyDate(b.block_date)}</strong> · {b.booking_time || 'Entire day'}<small>{b.reason}</small></div><Button variant="outline" disabled={busy} onClick={() => mutate(`admin/blocks/${b.id}`,'DELETE',undefined,'Availability restored.')}>Unblock</Button></div>)}</div></div>}
  {tab === 'enquiries' && <><div className="table-wrap"><table><thead><tr><th>Reference / customer</th><th>Car / product</th><th>Requirement</th><th>Contact</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="table-empty">Loading enquiries…</td></tr> : !enquiries.length ? <tr><td colSpan={4} className="table-empty">No custom enquiries yet.</td></tr> : enquiries.map(q => <tr key={q.id}><td>{q.reference}<small>{q.customer_name}</small><small>{q.mobile_number}</small><small>{q.email}</small></td><td>{q.car_manufacturer} {q.car_model}<small>{q.manufacturing_year} · {q.fuel_type}</small><small>{q.required_product}</small></td><td style={{whiteSpace:'pre-wrap',minWidth:230,maxWidth:380}}>{q.requirement}<small>Condition: {q.condition}</small>{q.uploaded_image_url && <Button variant="text" disabled={busy} onClick={() => openImage(q.id,'enquiries')}>View Photograph</Button>}</td><td><Button variant="subtle" href={whatsappUrl(`Hello ${q.customer_name}, this is RECO regarding your custom silencer enquiry ${q.reference}.`,q.mobile_number)} target="_blank" rel="noreferrer">WhatsApp</Button></td></tr>)}</tbody></table></div>{image && <div className="dashboard-panel"><img className="admin-image" src={image.url} alt="Custom silencer requirement photograph"/></div>}</>}
  <button className="text-link admin-refresh" disabled={loading} onClick={refresh}><FiRefreshCw/>{loading ? 'Refreshing…' : 'Refresh dashboard'}</button></section>;
}
