import { useState } from 'react';
import { FiPhone, FiMapPin, FiMail, FiClock, FiArrowUpRight } from 'react-icons/fi';
import { FaWhatsapp } from 'react-icons/fa';
import { PageIntro, Button, Field, SelectField, WhatsApp, BookingCTA, Eyebrow, ErrorNotice, Logo } from '../components/UI';
import { company } from '../data/catalog';
import { validMobile, whatsappUrl } from '../lib/shared';
export function EnquiryForm() {
  const [values, setValues] = useState({ name: '', mobile: '', type: '', message: '' }); const [errors, setErrors] = useState({}); const [ready, setReady] = useState(false);
  const update = e => { setReady(false); setValues({ ...values, [e.target.name]: e.target.value }); setErrors({ ...errors, [e.target.name]: '' }); };
  const text = `Hello RECO,\nName: ${values.name}\nMobile: ${values.mobile}\nEnquiry: ${values.type}\n${values.message}`;
  function submit(e) { e.preventDefault(); const next = {}; if (!values.name.trim()) next.name = 'Please enter your name.'; if (!validMobile(values.mobile)) next.mobile = 'Enter a valid 10-digit mobile number.'; if (!values.type) next.type = 'Choose an enquiry type.'; if (!values.message.trim()) next.message = 'Please tell us about your requirement.'; setErrors(next); if (!Object.keys(next).length) setReady(true); }
  return <form className="enquiry-form" noValidate onSubmit={submit}><h3>Send a product enquiry</h3><div className="form-grid"><Field name="name" label="Your name" value={values.name} onChange={update} autoComplete="name" error={errors.name} required maxLength={120}/><Field name="mobile" label="Mobile number" type="tel" value={values.mobile} onChange={update} autoComplete="tel" error={errors.mobile} required maxLength={20}/><div className="field-full"><SelectField label="Enquiry type" name="type" options={['Car-silencer product enquiry', 'Custom car-silencer enquiry', 'Car model & fitment', 'Booking enquiry']} value={values.type} onChange={update} error={errors.type} required/></div><Field className="field-full" label="How can we help?" name="message" error={errors.message}><textarea id="message" name="message" rows={4} maxLength={2000} value={values.message} onChange={update} placeholder="Your car model and the part you’re looking for…" required aria-invalid={Boolean(errors.message)}/></Field></div>{ready ? <div className="enquiry-ready" role="status"><p>Your enquiry is ready. Open WhatsApp to review and send it to RECO.</p><Button href={whatsappUrl(text)} target="_blank" rel="noreferrer"><FaWhatsapp/>Open WhatsApp<FiArrowUpRight/></Button></div> : <Button type="submit">Prepare WhatsApp Enquiry<FiArrowUpRight/></Button>}<p className="field-hint">Your message opens in WhatsApp for you to review and send.</p></form>;
}
export default function Contact() { return <><PageIntro eyebrow="CONTACT RECO" title="A good conversation starts here.">For car silencers, product enquiries and model-specific requirements, talk to our team in Calicut.</PageIntro><section className="section container contact-grid"><div><Logo/><div className="contact-block"><FiMapPin/><div><h2>Visit RECO</h2><p>{company.address}</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=East+Kallai+Cross+Road+Chalappuram+Calicut+673002" target="_blank" rel="noreferrer">Get directions<FiArrowUpRight/></a></div></div><div className="contact-block"><FiPhone/><div><h2>Call us</h2><a href="tel:+914952303961">0495 2303961</a><a href="tel:+919544922507">+91 95449 22507</a><a href="tel:+917025023317">+91 70250 23317</a></div></div><div className="contact-block"><FiMail/><div><h2>Write to us</h2><a href={`mailto:${company.email}`}>{company.email}</a></div></div><div className="contact-block"><FiClock/><div><h2>Business hours</h2><p>{company.businessHours || 'Please call to confirm opening hours before visiting.'}</p><p className="field-hint">Appointment requests: Monday–Saturday, in the listed booking slots.</p></div></div><WhatsApp variant="primary">WhatsApp RECO</WhatsApp></div><EnquiryForm/></section><section className="container map-section"><div className="map-heading"><Eyebrow>FIND US IN CALICUT</Eyebrow><p>East Kallai Cross Road · Chalappuram</p></div><iframe title="Map of East Kallai Cross Road, Chalappuram, Calicut" src="https://maps.google.com/maps?q=East%20Kallai%20Cross%20Road%20Chalappuram%20Calicut%20673002&t=&z=16&ie=UTF8&iwloc=&output=embed" width="100%" height="400" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><p className="field-hint">Map shows the supplied address area. Call RECO for exact arrival directions.</p></section><BookingCTA/></>; }
