import { Link } from 'react-router-dom';
import { FiArrowUpRight, FiArrowRight, FiCheckCircle, FiTarget, FiVolumeX, FiLayers, FiMapPin, FiPhone } from 'react-icons/fi';
import { Button, Reveal, Eyebrow, SectionHeading, BookingCTA, WhatsApp, EmptyCatalogue } from '../components/UI';
import { categories, company, supportedCars, visibleProducts } from '../data/catalog';
import { ProductCard } from './Products';
import { EnquiryForm } from './Contact';
export const qualities = [
  [FiTarget, 'Precision in every fit', 'Car-specific manufacturing, with attention to the dimensions that matter.'],
  [FiLayers, 'Built for the road ahead', 'Quality materials and careful workmanship for reliable car exhaust components.'],
  [FiVolumeX, 'Comfort in every drive', 'Silencers designed with exhaust-noise reduction and efficient flow in mind.'],
];
export default function Home() { return <>
  <section className={`hero ${company.heroImage ? 'hero-with-photo' : ''}`}><div className="container hero-grid"><div className="hero-copy"><Eyebrow light>CAR SILENCER SPECIALISTS · SINCE 1988</Eyebrow><h1>Premium Quality<br/>Silencers for<br/><em>Every Car.</em></h1><p>Precision-manufactured car silencers and exhaust components from Calicut since 1988.</p><div className="button-row"><Button to="/car-silencers" variant="teal">Explore Car Silencers<FiArrowUpRight/></Button><Button to="/book-a-slot" variant="ghost">Book a Slot<FiArrowRight/></Button></div><a className="hero-whatsapp" href="https://wa.me/919544922507?text=Hello%20RECO%2C%20I%20have%20a%20car-silencer%20enquiry." target="_blank" rel="noreferrer">WhatsApp Enquiry<FiArrowUpRight/></a></div><div className="hero-art">{company.heroImage ? <img className="hero-photo" src={company.heroImage} alt="Client-supplied RECO car silencer" width="900" height="900" fetchPriority="high"/> : <><div className="edition-label"><span>RATNA ENGINEERING<br/>CORPORATION</span><span>CALICUT<br/>KERALA, INDIA</span></div><div className="year-art"><span className="year-prefix">MANUFACTURING SINCE</span><span className="year-number">19<span>88</span></span><div className="year-caption"><span>Our legacy.<br/>Your confidence.</span><FiArrowUpRight/></div></div><div className="art-foot"><span>PRECISION. DURABILITY. FITMENT.</span><span>RECO®</span></div></>}</div></div><div className="hero-lower container"><span><FiCheckCircle/>Passenger-car specialists</span><span><FiCheckCircle/>Model-specific manufacturing</span><span><FiMapPin/>Made in Calicut</span><a href="tel:+914952303961">Call Now <FiArrowUpRight/></a></div></section>
  <section className="section container"><Reveal><SectionHeading eyebrow="ENGINEERED AROUND YOUR CAR" title="The right part. The right fit." link="Explore all products" to="/car-silencers">From the first pipe to the final note. Explore our car exhaust product categories.</SectionHeading></Reveal><div className="category-grid">{categories.slice(0, 4).map((c, i) => <Reveal key={c.name} delay={i * .06}><Link to={`/car-silencers?category=${encodeURIComponent(c.name)}`} className={`category-card category-${i}`}><div className="category-top"><span>0{i + 1} / EXHAUST COMPONENTS</span><FiArrowUpRight/></div><div className="category-statement">{c.short}</div><div><h3>{c.name}</h3><p>{c.detail}</p></div></Link></Reveal>)}</div></section>
  <section className="brand-strip"><div className="container"><div><Eyebrow>CAR BRANDS & MODELS</Eyebrow><h2>Tell us what you drive.</h2></div><p>Fitment starts with the details.<br/>Find your model or ask our team.</p><Button to="/car-models" variant="outline">Find My Car<FiArrowRight/></Button>{supportedCars.length > 0 && <div className="brand-list">{supportedCars.map(b => <span key={b.manufacturer}>{b.manufacturer}</span>)}</div>}</div></section>
  <section className="section container"><SectionHeading eyebrow="THE RECO DIFFERENCE" title="Good engineering. Quiet confidence."/><div className="quality-grid">{qualities.map(([Icon, title, text], i) => <Reveal key={title} className="quality" delay={i * .08}><span className="quality-icon"><Icon/></span><h3>{title}</h3><p>{text}</p><span className="quality-index">0{i + 1}</span></Reveal>)}</div></section>
  <section className="heritage-section"><div className="container heritage-grid"><Reveal className="heritage-year"><Eyebrow>ROOTED IN CALICUT</Eyebrow><strong>Since<br/><span>1988.</span></strong><p>A commitment that carries on.</p></Reveal><Reveal className="heritage-copy"><Eyebrow>OUR STORY</Eyebrow><h2>Built on experience.<br/>Shaped by precision.</h2><p>From our beginnings in 1988, Ratna Engineering Corporation has focused on one thing: making reliable car silencers and exhaust components.</p><p>Based in Calicut, we bring careful workmanship, quality materials and model-specific attention to every requirement.</p><Link to="/about" className="text-link">Get to know RECO<FiArrowUpRight/></Link></Reveal></div></section>
  <section className="section container"><SectionHeading eyebrow="FEATURED CAR SILENCERS" title="Find your car’s next silencer." link="View the catalogue" to="/car-silencers"/>{visibleProducts.length ? <div className="product-grid">{visibleProducts.slice(0, 3).map(p => <ProductCard key={p.id} product={p}/>)}</div> : <EmptyCatalogue/>}</section>
  <section className="container custom-feature"><div className="custom-feature-label"><span>MADE AROUND<br/>YOUR REQUIREMENT.</span><FiArrowUpRight/></div><div><Eyebrow>MODEL-SPECIFIC SOLUTIONS</Eyebrow><h2>Your car. Your requirement.<br/>Our manufacturing expertise.</h2><p>Have a specific silencer requirement? Share your car details and a photograph of the existing part. We’ll review the fitment, availability and price with you.</p><Button to="/custom-silencers">Custom Silencer Manufacturing<FiArrowUpRight/></Button></div></section>
  <BookingCTA/>
  <section className="section container enquiry-grid"><div><Eyebrow>WE’RE HERE TO HELP</Eyebrow><h2>Let’s talk<br/>car silencers.</h2><p>Have a product question? Get in touch with the RECO team.</p><a className="contact-inline" href="tel:+914952303961"><FiPhone/><span><small>CALL RECO</small>0495 2303961</span></a><div className="contact-inline"><FiMapPin/><span><small>VISIT US IN CALICUT</small>{company.address}</span></div></div><EnquiryForm/></section>
  </>; }
