import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { FiSearch, FiArrowUpRight, FiSliders } from 'react-icons/fi';
import { PageIntro, Button, WhatsApp, EmptyCatalogue, SelectField, BookingCTA } from '../components/UI';
import { categories, visibleProducts, fuelTypes } from '../data/catalog';
export function ProductCard({ product: p }) { return <article className="product-card"><div className="product-photo"><img src={p.image} alt={p.imageAlt || p.name} width="640" height="480" loading="lazy" decoding="async"/></div><div className="product-card-content"><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><dl><div><dt>Manufacturer</dt><dd>{p.manufacturer}</dd></div><div><dt>Model</dt><dd>{p.model}</dd></div><div><dt>Fuel type</dt><dd>{p.fuelType}</dd></div><div><dt>Availability</dt><dd>{p.availability}</dd></div></dl><WhatsApp text={`Hello RECO, please confirm price and availability for ${p.name}, ${p.manufacturer} ${p.model}, ${p.fuelType}.`} variant="primary">Request Price<FiArrowUpRight/></WhatsApp><div className="product-links"><Button to={`/book-a-slot?product=${encodeURIComponent(p.name)}`} variant="text">Book Inspection</Button><WhatsApp text={`Hello RECO, I would like to enquire about ${p.name}.`} variant="text">WhatsApp</WhatsApp></div></div></article>; }
export default function Products() {
  const [params, setParams] = useSearchParams(); const [search, setSearch] = useState('');
  const filters = Object.fromEntries(['manufacturer', 'model', 'fuelType', 'category', 'availability'].map(k => [k, params.get(k) || '']));
  const update = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key === 'manufacturer') next.delete('model'); setParams(next, { replace: true }); };
  const filtered = useMemo(() => visibleProducts.filter(p => Object.entries(filters).every(([k, v]) => !v || p[k] === v) && [p.name, p.manufacturer, p.model, p.description].join(' ').toLowerCase().includes(search.toLowerCase())), [search, params]);
  const manufacturers = [...new Set(visibleProducts.map(p => p.manufacturer))];
  const models = [...new Set(visibleProducts.filter(p => !filters.manufacturer || p.manufacturer === filters.manufacturer).map(p => p.model))];
  return <><PageIntro eyebrow="CAR SILENCERS" title="Precision, for your car.">Explore car silencers, mufflers and exhaust components. Tell us your model for confirmed fitment and pricing.</PageIntro><section className="section container catalogue-layout"><aside className="filter-panel"><h2><FiSliders/>Refine your search</h2><SelectField label="Car manufacturer" name="filter-manufacturer" placeholder="All manufacturers" options={manufacturers} value={filters.manufacturer} onChange={e => update('manufacturer', e.target.value)}/><SelectField label="Car model" name="filter-model" placeholder="All car models" options={models} value={filters.model} onChange={e => update('model', e.target.value)}/><SelectField label="Fuel type" name="filter-fuel" placeholder="All fuel types" options={fuelTypes} value={filters.fuelType} onChange={e => update('fuelType', e.target.value)}/><SelectField label="Product category" name="filter-category" placeholder="All categories" options={categories.map(c => c.name)} value={filters.category} onChange={e => update('category', e.target.value)}/><SelectField label="Availability" name="filter-availability" placeholder="Any availability" options={['Available', 'Made to order', 'Enquire']} value={filters.availability} onChange={e => update('availability', e.target.value)}/><button className="text-link" onClick={() => { setParams({}); setSearch(''); }}>Clear all filters</button></aside><div className="catalogue-results"><label className="searchbox"><FiSearch/><input aria-label="Search car silencers" placeholder="Search by product, car manufacturer or model" value={search} onChange={e => setSearch(e.target.value)}/></label><div className="results-bar"><span aria-live="polite">{filtered.length ? `${filtered.length} verified products` : 'Product availability confirmed on enquiry'}</span><span>PASSENGER CARS ONLY</span></div>{filtered.length ? <div className="product-grid">{filtered.map(p => <ProductCard key={p.id} product={p}/>)}</div> : <EmptyCatalogue/>}<div className="catalogue-note"><h3>{filters.category || 'Car exhaust products'}</h3><p>{categories.find(c => c.name === filters.category)?.detail || 'Our range covers car silencers, mufflers, exhaust pipes, tail pipes and model-specific assemblies.'} Contact RECO for current product photographs and a confirmed match for your car.</p></div></div></section><BookingCTA/></>;
}
