import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { FiArrowUpRight, FiPhone, FiMapPin, FiMenu, FiX, FiMail } from 'react-icons/fi';
import { FaWhatsapp } from 'react-icons/fa';
import { Logo, Button, WhatsApp } from './UI';
import { company } from '../data/catalog';
import { whatsappUrl } from '../lib/shared';
export const navLinks = [['/', 'Home'], ['/about', 'About'], ['/car-silencers', 'Car Silencers'], ['/car-models', 'Car Models'], ['/custom-silencers', 'Custom Manufacturing'], ['/contact', 'Contact']];
const titles = { '/': 'Premium Car Silencers · Calicut Since 1988', '/about': 'About Ratna Engineering Corporation', '/car-silencers': 'Car Silencers & Exhaust Products', '/car-models': 'Find Your Car Model', '/custom-silencers': 'Custom Silencer Manufacturing', '/book-a-slot': 'Book a Car Silencer Appointment', '/contact': 'Contact RECO in Calicut', '/admin': 'Staff Booking Dashboard' };
export default function Layout() {
  const [menu, setMenu] = useState(false); const location = useLocation(); const main = useRef(); const menuButton = useRef(); const firstRender = useRef(true);
  useEffect(() => {
    setMenu(false); window.scrollTo(0, 0);
    document.title = `${titles[location.pathname] || 'Page Not Found'} | RECO`;
    document.querySelector('meta[name="description"]').content = `${titles[location.pathname] || 'RECO'}. Premium car silencers and exhaust components from Ratna Engineering Corporation, Calicut. Established 1988. Call 0495 2303961.`;
    let robots = document.querySelector('meta[name="robots"]'); if (!robots) { robots = document.createElement('meta'); robots.name = 'robots'; document.head.appendChild(robots); } robots.content = location.pathname.startsWith('/admin') ? 'noindex,nofollow' : 'index,follow';
    const base = import.meta.env.VITE_SITE_URL; if (base) { let canonical = document.querySelector('link[rel="canonical"]'); if (!canonical) { canonical = document.createElement('link'); canonical.rel = 'canonical'; document.head.appendChild(canonical); } canonical.href = new URL(location.pathname, base).href; }
    if (!firstRender.current) main.current?.focus({ preventScroll: true }); firstRender.current = false;
  }, [location.pathname]);
  return <><a className="skip-link" href="#main">Skip to content</a><div className="topbar"><div className="container"><span>PRECISION MANUFACTURING. <span className="topbar-extra">LASTING CONFIDENCE.</span> SINCE 1988.</span><div><a href="https://www.google.com/maps/search/?api=1&query=East+Kallai+Cross+Road+Chalappuram+Calicut+673002" target="_blank" rel="noreferrer"><FiMapPin/>Calicut, Kerala</a><a href="tel:+914952303961"><FiPhone/>0495 2303961</a></div></div></div>
  <header className="site-header"><div className="container header-inner"><Link to="/" aria-label="RECO home"><Logo/></Link><button ref={menuButton} className="menu-toggle" aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu} aria-controls="main-nav" onClick={() => setMenu(!menu)}>{menu ? <FiX/> : <FiMenu/>}</button><nav id="main-nav" className={menu ? 'nav open' : 'nav'} aria-label="Main navigation" onKeyDown={e => { if (e.key === 'Escape') { setMenu(false); menuButton.current?.focus(); } }}>{navLinks.map(([path, name]) => <NavLink end={path === '/'} key={path} to={path}>{name}</NavLink>)}<NavLink to="/book-a-slot" className="nav-book">Book a Slot<FiArrowUpRight/></NavLink><a className="nav-wa" href={whatsappUrl('Hello RECO, I have a car-silencer enquiry.')} aria-label="WhatsApp RECO" target="_blank" rel="noreferrer"><FaWhatsapp/></a></nav></div></header>
  <main ref={main} id="main" tabIndex={-1}><Outlet/></main>
  <footer className="footer"><div className="container footer-grid"><div className="footer-brand"><Link to="/"><Logo light/></Link><p>RECO – Ratna Engineering Corporation manufactures premium-quality silencers and exhaust components for cars in Calicut.</p><span className="est-tag">ESTABLISHED 1988</span></div><div><h3>Explore RECO</h3>{navLinks.slice(1).map(([p, n]) => <Link key={p} to={p}>{n}</Link>)}<Link to="/book-a-slot">Book a Slot</Link></div><div><h3>Car exhaust products</h3>{['Car Silencers', 'Car Mufflers', 'Exhaust Pipes', 'Tail Pipes', 'Rear Silencer Assemblies'].map(c => <Link key={c} to={`/car-silencers?category=${encodeURIComponent(c)}`}>{c}</Link>)}</div><div><h3>Let’s talk</h3><a href="tel:+914952303961">0495 2303961</a><a href="tel:+919544922507">+91 95449 22507</a><a href="tel:+917025023317">+91 70250 23317</a><a className="footer-email" href={`mailto:${company.email}`}><FiMail/>{company.email}</a><p>{company.address}</p><WhatsApp variant="footer">Chat on WhatsApp<FiArrowUpRight/></WhatsApp></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} RECO – Ratna Engineering Corporation.</span><span>Made with precision. In Calicut.</span><Link to="/admin">Staff login</Link></div></footer>
  <div className="mobile-contact"><a href="tel:+914952303961"><FiPhone/>Call Now</a><Link to="/book-a-slot">Book a Slot<FiArrowUpRight/></Link><a href={whatsappUrl('Hello RECO, I have a car-silencer enquiry.')} target="_blank" rel="noreferrer"><FaWhatsapp/>WhatsApp</a></div></>;
}
